/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package souzoudev.bojsolved;

import souzoudev.bojsolved.problem.P4344;

public class App {
    public static void main(String[] args) {
        P4344.solution(args);
    }
}
