/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package souzoudev.bojsolved;

import souzoudev.bojsolved.problem.P1157;

public class App {
    public static void main(String[] args) {
        P1157.solution(args);
    }
}
